version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  ml-environment:
    image: python:3.12.6  # Asegúrate de que la versión de Python sea la que seleccionaste
    container_name: ml-environment
    ports:
      - "8080:8080"  # El puerto configurado para Jupyter Notebook
    volumes:
      - .:/app  # Mapea la carpeta actual al contenedor
    working_dir: /app
    command: jupyter notebook --ip=0.0.0.0 --port=8080 --no-browser --allow-root
    depends_on:
      - kafka

